spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ojik
    username: ${DB_USERNAME:ojik}
    password: ${DB_PASSWORD:ojik}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

social:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me

auth:
  signup-token:
    secret-key: ${SIGNUP_TOKEN_SECRET_KEY}
    expiration: ${SIGNUP_TOKEN_EXPIRATION:15m}
