spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ojik
    username: ${DB_USERNAME:ojik}
    password: ${DB_PASSWORD:ojik}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
